# Parameters can be found at:
# https://docs.prylabs.network/docs/prysm-usage/parameters/

accept-terms-of-use: yes

datadir: /data

rpc-host: prysm-beacon-node

monitoring-host: 0.0.0.0

http-web3provider: http://geth-node:8545

pyrmont: yes
